// <auto-generated />
namespace MudarService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09262 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09262));
        
        string IMigrationMetadata.Id
        {
            get { return "201709260718548_0926-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
